
 development:
  adapter: mysql2
  encoding: utf8
  database: Cms_development
  pool: 5
  username: Cms
  password: exa10sept
  host: localhost


 production:
  adapter: mysql2
  encoding: utf8
  database: Cms_development
  pool: 5
  username: Cms
  password: exa10sept
  host: localhost
  

  test:
  adapter: mysql2
  encoding: utf8
  database: Cms_development
  pool: 5
  username: Cms
  password: exa10sept
  host: localhost
 